name: Deploy to DigitalOcean App Platform

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to DigitalOcean App Platform
        uses: digitalocean/app_action@v1.1.5
        with:
          app_name: ${{ secrets.DO_APP_NAME }}
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
